# Generated by Django 5.0.2 on 2024-02-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpeg', upload_to='media/profile_images'),
        ),
    ]
